[project]
name = "easysam"
version = "1.0.0"
description = "Cloud structure for simplified SAM templating (EASYSAM)"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "boto3>=1.38.15",
    "click>=8.2.0",
    "jinja2-cli[yaml]>=0.8.2",
]

[project.scripts]
easysam = "easysam.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/easysam"]

[dependency-groups]
dev = [
    "pip>=25.1.1",
]
